# docker-compose.yml
# version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: twi_db
    restart: always
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        # localhost:5432 -> container:5432
      - "5432:5432"

  backend:
    build: backend/
    container_name: twi_backend
    #command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    #volumes:
    #- .:/app
    ports:
        # localhost:8090 -> container:8000
      - "8090:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: djangodb
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 12345
    depends_on:
    - db

  web:
    build: frontend/
    container_name: twi_frontend
    ports:
      # localhost:8000 -> container:8000
      - "8000:80"
    environment:
      BACKEND_URL: backend:8000
    depends_on:
    - backend

volumes:
  postgres_data: