apiVersion: v2
name: Twi
description: Umbrella chart for PyTwi App (backend + frontend)
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: backend
  version: 0.0.1
  repository: "file://backend"
- name: frontend
  version: 0.0.1
  repository: "file://frontend"
