apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    alloy.io/scrape: "true"
    loki.io/logs: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.listenPort | default "8000" | quote }}
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
      {{- include "backend.labels" . | nindent 8 }}
      annotations:
        alloy.io/scrape: "true"
        loki.io/logs: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.service.listenPort | default "8000" | quote }}
        prometheus.io/path: "/metrics"
    spec:
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "backend.fullname" . }}
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        - name: init-script
          configMap:
            name: {{ .Release.Name }}-init-script
            defaultMode: 0755
      #securityContext:
      #  fsGroup: 200
      containers:
        - name: backend
          image:  pybe #"{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.listenPort | default "8000" }}
              name: http
          env:
            - name: POSTGRES_DB
              value: djangodb
            - name: POSTGRES_HOST
              value: localhost
            - name:  POSTGRES_USER
              value: django
            - name:  POSTGRES_PASSWORD
              value: "12345"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
                path: /
                port: {{ .Values.service.listenPort | default "8000" }}
            periodSeconds: 30
          livenessProbe:
            httpGet:
                path: /
                port: {{ .Values.service.listenPort | default "8000" }}
            initialDelaySeconds: 60
            periodSeconds: 30
        - name: db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: db
          env:
            - name: POSTGRES_DB
              value: djangodb
            - name:  POSTGRES_USER
              value: django
            - name:  POSTGRES_PASSWORD
              value: "12345"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
