apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port | default "8000" }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default "8000" }}
      targetPort: {{ .Values.service.listenPort | default "8000" }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}