{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name | quote }}
  labels:
    release: kps 
    app: {{ .Release.Name }}
    {{- include "labels" . | nindent 4 }}
spec:
  jobLabel: {{ .Release.Name }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Chart.Name | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app: {{ .Release.Name | quote }}
  endpoints:
  - port: http
    path: /metrics
    scheme: http
    targetPort: {{ .Values.service.listenPort | default "8000" }}
    interval: 15s
{{- end }}